# Generated by Django 5.1.1 on 2024-10-03 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_nombre', models.CharField(max_length=100)),
                ('hotel_direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_nombre', models.CharField(max_length=100)),
                ('admin_apellidos', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=150)),
                ('admin_telefono', models.CharField(max_length=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_apellidos', models.CharField(max_length=100)),
                ('cliente_email', models.EmailField(max_length=150)),
                ('cliente_telefono', models.CharField(max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_nombre', models.CharField(max_length=100)),
                ('empleado_apellidos', models.CharField(max_length=100)),
                ('empleado_rol', models.CharField(max_length=50)),
                ('empleado_email', models.EmailField(max_length=150)),
                ('empleado_telefono', models.CharField(max_length=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion_numero', models.CharField(max_length=10)),
                ('habitacion_categoria', models.CharField(max_length=50)),
                ('habitacion_descripcion', models.TextField(blank=True, null=True)),
                ('habitacion_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitacion_imagen', models.ImageField(blank=True, null=True, upload_to='img/habitaciones/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_fecha', models.DateField(auto_now_add=True)),
                ('reserva_fecha_inicio', models.DateField()),
                ('reserva_fecha_fin', models.DateField()),
                ('reserva_total_dias', models.IntegerField(blank=True, null=True)),
                ('reserva_estado', models.CharField(default='Pendiente', max_length=50)),
                ('tipo_pago', models.CharField(default='Tarjeta de Crédito', max_length=100)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.habitacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_fecha', models.DateField()),
                ('pago_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_metodo', models.CharField(max_length=50)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('administrador', 'Administrador')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
