# Generated by Django 4.2.23 on 2025-09-28 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='administrador',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'administrador'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
