# Generated by Django 5.1.1 on 2024-10-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_administrador_usuario_alter_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='habitacion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/habitaciones/'),
        ),
    ]
