# Generated by Django 5.1.1 on 2024-10-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_habitacion_habitacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo_pago',
            field=models.CharField(default='Tarjeta de Crédito', max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='reserva_estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='reserva_fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='reserva_total_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
